extends:
  file: ../maven/pipeline.yaml
pipelines:
  pullRequest:
    build:
      replace: true
      steps:
      - sh: mvn versions:set -DnewVersion=$PREVIEW_VERSION
        name: set-version
      - sh: ls *.sql | sort -r | head -1 | sed -e 's/_.*//' > DB_VERSION
        name: database-schema-version
        dir: database/rollouts
      - sh: mvn clean install
        name: mvn-install
      #        - sh: mvn liberty:create-server liberty:install-feature liberty:install-apps liberty:start-server failsafe:integration-test liberty:stop-server failsafe:verify
      - sh: echo doing integration test; sleep 3
        name: mvn-liberty-integration-test
      - sh: skaffold version
        name: skaffold-version
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
        name: container-build
#    promote:
  #   include wait step, then execute system test
#      - name: system-test
#        steps:
#        #          - sh: mvn failsafe:integration-test failsafe:verify -Dliberty.test.host=jenkins-x-quickstart-liberty.jx-production.34.90.141.229.nip.io -Dliberty.test.port=80
#        - sh: echo doing system test; sleep 3
#          name: mvn-liberty-integration-test

  release:
    setVersion:
      replace: true
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        name: next-version
      - sh: ls *.sql | sort -r | head -1 | sed -e 's/_.*//' > DB_VERSION
        name: database-schema-version
        dir: database/rollouts
      - sh: mvn versions:set -DnewVersion=\$(cat VERSION)
        name: set-version
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      replace: true
      steps:
      - sh: mvn clean deploy
        name: mvn-deploy
      #        - sh: mvn liberty:create-server liberty:install-feature liberty:install-apps liberty:start-server failsafe:integration-test liberty:stop-server failsafe:verify
      - sh: echo doing integration test; sleep 3
        name: mvn-liberty-integration-test
      - sh: skaffold version
        name: skaffold-version
      - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
        name: container-build
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
#    promote:
  #   include wait step, then execute system test
  #      - name: system-test
  #        steps:
  #        #          - sh: mvn failsafe:integration-test failsafe:verify -Dliberty.test.host=jenkins-x-quickstart-liberty.jx-production.34.90.141.229.nip.io -Dliberty.test.port=80
  #        - sh: echo doing system test; sleep 3
  #          name: mvn-liberty-integration-test
